# Generated by Django 4.1.1 on 2022-09-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='upload',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
