# Generated by Django 4.1.1 on 2022-09-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foto_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='upload',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='nombre',
        ),
    ]
