# Generated by Django 4.1.1 on 2022-10-03 18:20

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_carrousel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='carrousel',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[450, 450], upload_to='img_carousel'),
        ),
    ]
