# Generated by Django 4.1.1 on 2022-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_carrousel_entry_date_alter_carrousel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
