# Generated by Django 4.1.1 on 2022-10-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_foto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='aviso',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=255),
        ),
    ]
