# Generated by Django 4.1.1 on 2022-10-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_contacto_aviso_alter_contacto_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='motivo',
            field=models.CharField(choices=[('0', 'Consulta general'), ('1', 'Precios'), ('2', 'Disponibilidad'), ('3', 'Servicios')], max_length=1, null=True),
        ),
    ]
